// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhkpjlnwwysbunmhlcsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impoa3BqbG53d3lzYnVubWhsY3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTk4NDYsImV4cCI6MjA2ODAzNTg0Nn0.rVtv2bvpzPXW6ZxYdVZAURz8SsY-O2CeetSFnJwzSxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});